first commit on review branch
VICTOR-CHUKWU/Review-code pull request #1
Opened 2021-08-21 15:55 UTC by VICTOR-CHUKWU

review code branch is the body of the page

2021-08-21 16:00 UTC, VICTOR-CHUKWU commented on index.html
> +        <textarea name="textarea" id="textarea" cols="30" rows="10"></textarea>
it won't be nice if a user submits empty text, textarea should be required

2021-08-21 16:03 UTC, VICTOR-CHUKWU reviewed
nice work so far just make the necessary changes

2021-08-21 16:03 UTC, VICTOR-CHUKWU commented on index.html
> +    - The freeCodeCamp Team
kindly delete it since it's not needed

2021-08-21 16:21 UTC, descholar-ceo requested changes
Hi @VICTOR-CHUKWU , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [Optional] For the review summary, I would suggest you to use a detailed template, fpr example, you can use this template of mine

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-21 16:21 UTC, descholar-ceo commented on index.html
> +        <textarea name="textarea" id="textarea" cols="30" rows="10"></textarea>
- [ ] I would suggest you explain concisely why you requested this change, so that it will be easy for him / her to implement you requested changes

2021-08-21 16:21 UTC, descholar-ceo commented on index.html
> +    - The freeCodeCamp Team
- [ ] I would suggest you explain concisely why you requested this change, so that it will be easy for him / her to implement you requested changes

2021-08-21 21:07 UTC, VICTOR-CHUKWU reviewed
good job so far kindly look into what has been pointed out

2021-08-21 21:07 UTC, VICTOR-CHUKWU commented on index.html
> +        <textarea name="textarea" id="textarea" cols="30" rows="10"></textarea>
it would be nice if we can't send an empty message, so please make this field also required

2021-08-21 21:07 UTC, VICTOR-CHUKWU commented on index.html
> +    - The freeCodeCamp Team
kindly delete this as it is said to delete if your code works in chrome and I feel its a guide that you have read, so to make your code neater kindly remove

2021-08-22 00:02 UTC, descholar-ceo approved these changes
Hi @VICTOR-CHUKWU , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-22 10:13 UTC, merged